export const PROFESSIONAL_REGISTRATION = [
  { label: "CRM", value: "CRM" },
  { label: "COREN", value: "COREN" },
];

export const WORKING_FIELD = [
  { icon: "Doctor", description: "Médico Generalista" },
  { icon: "Pipette", description: "Dermatologista" },
  { icon: "Nurse", description: "Enfermeiro" },
];

export const BRAZILIAN_STATES = [
  { label: "AC", value: "ac" },
  { label: "AL", value: "al" },
  { label: "AP", value: "ap" },
  { label: "AM", value: "am" },
  { label: "BA", value: "ba" },
  { label: "CE", value: "ce" },
  { label: "DF", value: "df" },
  { label: "ES", value: "es" },
  { label: "GO", value: "go" },
  { label: "MA", value: "ma" },
  { label: "MT", value: "mt" },
  { label: "MS", value: "ms" },
  { label: "MG", value: "mg" },
  { label: "PA", value: "pa" },
  { label: "PB", value: "pb" },
  { label: "PR", value: "pr" },
  { label: "PE", value: "pe" },
  { label: "PI", value: "pi" },
  { label: "RJ", value: "rj" },
  { label: "RN", value: "rn" },
  { label: "RS", value: "rs" },
  { label: "RO", value: "ro" },
  { label: "RR", value: "rr" },
  { label: "SC", value: "sc" },
  { label: "SP", value: "sp" },
  { label: "SE", value: "se" },
  { label: "TO", value: "to" },
];

export const REGISTER_FIELDS = [
  {
    label: "Registro Profissional",
    placeholder: "Conselho",
    options: PROFESSIONAL_REGISTRATION,
    value: "council" as const,
    errorKey: "council",
  },
  {
    label: "",
    placeholder: "Estado",
    options: BRAZILIAN_STATES,
    value: "state" as const,
    errorKey: "state",
  },
];

export const COUNCIL_VALIDATION = {
  CRM: { min: 5, max: 6 },
  COREN: { min: 6, max: 7 },
  default: { min: 5, max: 8 },
};

export const VALID_AREA_CODES = [
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "21",
  "22",
  "24",
  "27",
  "28",
  "31",
  "32",
  "33",
  "34",
  "35",
  "37",
  "38",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "51",
  "53",
  "54",
  "55",
  "61",
  "62",
  "64",
  "63",
  "65",
  "66",
  "67",
  "68",
  "69",
  "71",
  "73",
  "74",
  "75",
  "77",
  "79",
  "81",
  "87",
  "82",
  "83",
  "84",
  "85",
  "88",
  "86",
  "89",
  "91",
  "93",
  "94",
  "92",
  "97",
  "95",
  "96",
  "98",
  "99",
];
